set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN P17 [get_ports clk]

set_property PACKAGE_PIN R11 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property PACKAGE_PIN V1 [get_ports rst_track]
set_property IOSTANDARD LVCMOS33 [get_ports rst_track]


set_property DRIVE 12 [get_ports speaker]
set_property IOSTANDARD LVCMOS33 [get_ports speaker]
set_property PACKAGE_PIN T1 [get_ports speaker]

set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
set_property PACKAGE_PIN R1 [get_ports {sel[0]}]
set_property PACKAGE_PIN N4 [get_ports {sel[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {sel_mode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel_mode[1]}]
set_property PACKAGE_PIN M4 [get_ports {sel_mode[0]}]
set_property PACKAGE_PIN R2 [get_ports {sel_mode[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {music_id[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {music_id[1]}]
set_property PACKAGE_PIN P4 [get_ports {music_id[0]}]
set_property PACKAGE_PIN P5 [get_ports {music_id[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {user[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {user[1]}]
set_property PACKAGE_PIN P2 [get_ports {user[0]}]
set_property PACKAGE_PIN P3 [get_ports {user[1]}]

set_property PACKAGE_PIN K5 [get_ports key_clk]
set_property PACKAGE_PIN L4 [get_ports key_data]
set_property IOSTANDARD LVCMOS33 [get_ports key_clk]
set_property IOSTANDARD LVCMOS33 [get_ports key_data]
set_property PACKAGE_PIN K2 [get_ports {led[0]}]
set_property PACKAGE_PIN J2 [get_ports {led[1]}]
set_property PACKAGE_PIN J3 [get_ports {led[2]}]
set_property PACKAGE_PIN H4 [get_ports {led[3]}]
set_property PACKAGE_PIN J4 [get_ports {led[4]}]
set_property PACKAGE_PIN G3 [get_ports {led[5]}]
set_property PACKAGE_PIN G4 [get_ports {led[6]}]

set_property PACKAGE_PIN M6 [get_ports SDO]
set_property IOSTANDARD LVCMOS33 [get_ports SDO]

set_property IOSTANDARD LVCMOS33 [get_ports {digital_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_en[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_data[0]}]
set_property PACKAGE_PIN E1 [get_ports {digital_en[1]}]
set_property PACKAGE_PIN D4 [get_ports {digital_data[7]}]

set_property PACKAGE_PIN G6 [get_ports {digital_en[0]}]

set_property PACKAGE_PIN F1 [get_ports {digital_en[2]}]
set_property PACKAGE_PIN G1 [get_ports {digital_en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_en[3]}]

set_property PACKAGE_PIN E3 [get_ports {digital_data[6]}]
set_property PACKAGE_PIN D3 [get_ports {digital_data[5]}]
set_property PACKAGE_PIN F4 [get_ports {digital_data[4]}]
set_property PACKAGE_PIN F3 [get_ports {digital_data[3]}]
set_property PACKAGE_PIN E2 [get_ports {digital_data[2]}]
set_property PACKAGE_PIN D2 [get_ports {digital_data[1]}]
set_property PACKAGE_PIN H2 [get_ports {digital_data[0]}]



set_property IOSTANDARD LVCMOS33 [get_ports digital_en3]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_data3[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_data3[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_data3[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_data3[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_data3[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_data3[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_data3[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_data3[2]}]
set_property PACKAGE_PIN G2 [get_ports digital_en3]
set_property PACKAGE_PIN B4 [get_ports {digital_data3[7]}]
set_property PACKAGE_PIN A4 [get_ports {digital_data3[6]}]
set_property PACKAGE_PIN A3 [get_ports {digital_data3[5]}]
set_property PACKAGE_PIN B1 [get_ports {digital_data3[4]}]
set_property PACKAGE_PIN A1 [get_ports {digital_data3[3]}]
set_property PACKAGE_PIN B3 [get_ports {digital_data3[2]}]
set_property PACKAGE_PIN B2 [get_ports {digital_data3[1]}]
set_property PACKAGE_PIN D5 [get_ports {digital_data3[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {color_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {color_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {color_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {color_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {color_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {color_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {color_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports vs]
set_property IOSTANDARD LVCMOS33 [get_ports {color_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {color_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {color_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {color_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {color_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports hs]
set_property PACKAGE_PIN C5 [get_ports {color_r[2]}]
set_property PACKAGE_PIN B6 [get_ports {color_g[0]}]
set_property PACKAGE_PIN E5 [get_ports {color_b[2]}]
set_property PACKAGE_PIN C6 [get_ports {color_r[1]}]
set_property PACKAGE_PIN F5 [get_ports {color_r[0]}]
set_property PACKAGE_PIN C7 [get_ports {color_b[0]}]
set_property PACKAGE_PIN E7 [get_ports {color_b[3]}]
set_property PACKAGE_PIN C4 [get_ports vs]
set_property PACKAGE_PIN D8 [get_ports {color_g[3]}]
set_property PACKAGE_PIN A5 [get_ports {color_g[2]}]
set_property PACKAGE_PIN E6 [get_ports {color_b[1]}]
set_property PACKAGE_PIN B7 [get_ports {color_r[3]}]
set_property PACKAGE_PIN A6 [get_ports {color_g[1]}]
set_property PACKAGE_PIN D7 [get_ports hs]


